name = "SuiteSparseGraphBLAS"
uuid = "c2e53296-7b14-11e9-1210-bddfa8111e1d"
authors = ["Abhinav Mehndiratta <abhinavmehndiratta@gmail.com>"]
version = "0.2.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
GraphBLASInterface = "5f047416-9681-11e9-0804-033d9936201f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinaryProvider = "0.5"
julia = "1"
