name = "SuiteSparseGraphBLAS"
uuid = "c2e53296-7b14-11e9-1210-bddfa8111e1d"
authors = ["Will Kimmerer <wrkimmerer@outlook.com", "Abhinav Mehndiratta <abhinavmehndiratta@gmail.com>"]
version = "0.4.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ContextVariablesX = "6add18c4-b38d-439d-96f6-d6bc489c04c5"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SSGraphBLAS_jll = "7ed9a814-9cab-54e9-8e9e-d9e95b4d61b1"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
SSGraphBLAS_jll = "5.1.2"
julia = "1.6"
CEnum = "0.4.1"
ContextVariablesX = "0.1.1"
MacroTools = "0.5.6"
